### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by josephfeleke** [muhrahmatullah/adr_in_app_review#1]
im testing your sample code and i changed this codes to true as you said for testing 

bool isTest = **true**

 final response = await _channel.invokeMethod('startInAppReview');
        return **true**;

final response = await _channel.invokeMethod('startInAppReview');
        return **true**;

but still the rating view is not popping up 

this is the log

I/PlayCore( 4368): UID: [10086]  PID: [4368] ReviewService : requestInAppReview (com.rahmat.app.inappreviewsample)
I/PlayCore( 4368): UID: [10086]  PID: [4368] ReviewService : Initiate binding to the service.
I/PlayCore( 4368): UID: [10086]  PID: [4368] ReviewService : ServiceConnectionImpl.onServiceConnected(ComponentInfo{com.android.vending/com.google.android.finsky.inappreviewservice.InAppReviewService})
I/PlayCore( 4368): UID: [10086]  PID: [4368] ReviewService : linkToDeath

**Comment by muhrahmatullah** [comment]
Hi @josephfeleke the variable `isTest` is actually used for unit test purposed, if you test your app in debug mode, the review dialog won't show up as described [here](https://developer.android.com/guide/playcore/in-app-review/test) in order to test it you should upload the apk in your playstore console

**Comment by josephfeleke** [comment]
is there any other way to know that the review dialog is working besides uploading it to the playstore?
and do you have any test apk already uploaded to playstore so i can test it?

**Comment by muhrahmatullah** [comment]
If the method call success then it should be works, currently I don't have test apk uploaded to playstore yet I managed to test it in my internal test track. as you can see in the readme(attached picture)

**Comment by muhrahmatullah** [comment]
no further comment, will close this issue
